//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment5.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assignment5.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=localhost;Initial Catalog=VideoGameReviews;Integrated Security=True;TrustServerCertificate=True.
        /// </summary>
        internal static string CONNECTION_STRING {
            get {
                return ResourceManager.GetString("CONNECTION_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Games.
        /// </summary>
        internal static string QUERY_ALL_GAMES {
            get {
                return ResourceManager.GetString("QUERY_ALL_GAMES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Reviews.
        /// </summary>
        internal static string QUERY_ALL_REVIEWS {
            get {
                return ResourceManager.GetString("QUERY_ALL_REVIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT UserID FROM Users;.
        /// </summary>
        internal static string QUERY_ALL_USER_ID {
            get {
                return ResourceManager.GetString("QUERY_ALL_USER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(UserID) AS UserCount FROM Users WHERE Email = @Email;.
        /// </summary>
        internal static string QUERY_EXISTING_USERS {
            get {
                return ResourceManager.GetString("QUERY_EXISTING_USERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Users WHERE.
        /// </summary>
        internal static string QUERY_USER_CREDENTIAL {
            get {
                return ResourceManager.GetString("QUERY_USER_CREDENTIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT FirstName FROM Users WHERE.
        /// </summary>
        internal static string QUERY_USER_NAME {
            get {
                return ResourceManager.GetString("QUERY_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spDeleteGame.
        /// </summary>
        internal static string SP_DELETE_GAME {
            get {
                return ResourceManager.GetString("SP_DELETE_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spDeleteReview.
        /// </summary>
        internal static string SP_DELETE_REVIEW {
            get {
                return ResourceManager.GetString("SP_DELETE_REVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spDeleteUser.
        /// </summary>
        internal static string SP_DELETE_USER {
            get {
                return ResourceManager.GetString("SP_DELETE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spInsertNewGame.
        /// </summary>
        internal static string SP_INSERT_GAME {
            get {
                return ResourceManager.GetString("SP_INSERT_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spInsertNewReview.
        /// </summary>
        internal static string SP_INSERT_REVIEW {
            get {
                return ResourceManager.GetString("SP_INSERT_REVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spInsertNewUser.
        /// </summary>
        internal static string SP_INSERT_USER {
            get {
                return ResourceManager.GetString("SP_INSERT_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spUpdateGame.
        /// </summary>
        internal static string SP_UPDATE_GAME {
            get {
                return ResourceManager.GetString("SP_UPDATE_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spUpdateReview.
        /// </summary>
        internal static string SP_UPDATE_REVIEW {
            get {
                return ResourceManager.GetString("SP_UPDATE_REVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spUpdateUser.
        /// </summary>
        internal static string SP_UPDATE_USER {
            get {
                return ResourceManager.GetString("SP_UPDATE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wererwer.
        /// </summary>
        internal static string TES {
            get {
                return ResourceManager.GetString("TES", resourceCulture);
            }
        }
    }
}
